attack_label_trans: all2one
attack_target: 0
pratio: 0.2
selected_layer_name: linear
selected_layer_param_name: linear.weight
num_neuron: 2
mask_path: ./resource/trojannn/apple4.png
neuron_target_values: 100
mask_update_iters: 1000
attack: trojannn
patch_mask_path: ./resource/badnet/trigger_image.png
dataset: cifar10
dataset_path: data
model: resnet18_xai
random_seed: 10
num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
device: cuda:0
client_optimizer: sgd
frequency_save: 0
batch_size: 256
lr: 0.01
lr_scheduler: CosineAnnealingLR
sgd_momentum: 0.9
wd: 0.0005
epochs: 20
pretrained: False
pretrain_model_path: record_badnet/clean_cifar_resnet_01/clean_model.pt