attack: refool
attack_label_trans: all2one
attack_target: 0
r_adv_img_folder_path: ./resource/refool/Refool-SelectedReflectionImages/selected_out-images
pratio: 0.2
ghost_rate: 0.49
alpha_t: 0.4
offset:
  - 0
  - 0
sigma: -1
ghost_alpha: -1
clean_label: False
dataset: cifar10
dataset_path: data
model: resnet18_xai
random_seed: 10
num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
device: cuda:0
client_optimizer: sgd
frequency_save: 0
batch_size: 256
lr: 0.01
lr_scheduler: CosineAnnealingLR
sgd_momentum: 0.9
wd: 0.0005
epochs: 25
pretrained: True