attack_label_trans: all2one
attack_target: 0
pratio: 0.1
attack: badnet
patch_mask_path: ./resource/badnet/trigger_image.png
dataset: mnist
dataset_path: data
model: lenet_mnist
random_seed: 56
num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
device: cuda:0
client_optimizer: sgd
frequency_save: 0
batch_size: 128
lr: 0.01
lr_scheduler: CosineAnnealingLR
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
epochs: 25