attack_label_trans: all2one
attack_target: 0
pratio: 0.2
attack: blended
attack_trigger_img_path: ./resource/blended/hello_kitty.jpeg
attack_train_blended_alpha: 0.2
attack_test_blended_alpha: 0.2
dataset: svhn
dataset_path: data
model: resnet18_xai
random_seed: 20
num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
device: cuda:0
client_optimizer: sgd
frequency_save: 0
batch_size: 256
lr: 0.008
lr_scheduler: CosineAnnealingLR
sgd_momentum: 0.9
wd: 0.0005
epochs: 15
pretrained: True